### ISSUE TITLE
variable naming

### ISSUE THREAD

**Issue by aditya-gore** [am-Anmol/E-Library#2]
` var Bname = document.forms['addBook']["BookName"].value;
    if (Bname.length == 0){
        seterror("bname", "*Book Name cannot be null!");
        returnval = false;
    }     
    var Aname = document.forms['addBook']["BookAuthor"].value;
    if (Aname.length == 0){
        seterror("Aname", "*Book Author cannot be null!");
        returnval = false`### 

--> Assign descriptive names to variables. Common convention is to use camelCase ex- bookName, authorName

**Comment by am-Anmol** [comment]
Replaced naming convention to camelCase.
