### ISSUE TITLE
labels for sorting

### ISSUE THREAD

**Issue by aditya-gore** [am-Anmol/E-Library#4]
instead of A-Z or Z-A use something more meaningful like ascending or descending, or better use an icon or image.

**Comment by am-Anmol** [comment]
Replaced Sorting label to ascending or descending
<img width="947" alt="Sorting 1" src="https://user-images.githubusercontent.com/48876126/116134901-11715780-a6ee-11eb-8e22-e9c832d3e122.png">
<img width="946" alt="Sorting 2" src="https://user-images.githubusercontent.com/48876126/116134905-1209ee00-a6ee-11eb-83e5-4cad8cb88184.png">
